### ISSUE TITLE
No Local GPU

### ISSUE THREAD

**Issue by litaws** [Kenza-AI/sagify#119]
Hi. 
First, this is a great piece of software! really enjoyed it!
A teammate made you demo work on his local machine (with CUDA enabled), and then pushed it seamlessly to the could where is also worked.
Alas, I do not have a GPU on my MacBook, so cannot use a cuda-docker locally.

How would you recommend to solve this?

**Comment by pm3310** [comment]
Hi @litaws ,

Thank you :-) 
As long as there's no CUDA-supported GPU on your MacBook, you cannot train your model with GPU via Sagify. 

I suggest making your code robust so that to use the CPU if no GPU is available. Then, you can train your model locally using Sagify with a subset of data (this will use the local CPU). Of course, the model will not be high quality. Then, you can use Sagify to train the same model on an ec2 machine with CUDA-supported GPU.

I hope this helps.

Thanks

**Comment by litaws** [comment]
Thanks!
